apiVersion: v1
data:
  template-production.json: |
    {
      "database": {
        "engine": "mysql",
        "host": "db",
        "name": "npm",
        "user": "npm",
        "password": "npm",
        "port": 3306
      }
    }
kind: ConfigMap
metadata:
  name: npm-config
  namespace: npm
  labels:
    app: nginx-proxy-manager
